#!/usr/bin/env bash
# Copyright (c) PyPTO Contributors.
# This program is free software, you can redistribute it and/or modify it under the terms and conditions of
# CANN Open Software License Agreement Version 2.0 (the "License").
# Please refer to the License for details. You may not use this file except in compliance with the License.
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
# See LICENSE in the root of the software repository for the full text of the License.
# -----------------------------------------------------------------------------------------------------------
#
# Write $PREFIX/activate.sh — the one entry point into a deployed bundle.
# Runs INSIDE the build container. Kept out of the Dockerfile because a shell
# heredoc spanning several Dockerfile lines only parses under BuildKit's own
# heredoc form, and the quoting needed to survive both parsers is unreadable.

set -euo pipefail

: "${PREFIX:?PREFIX must be set}"

# $PREFIX is written in as a literal, not derived from BASH_SOURCE at source
# time. activate.sh is also sourced by task-submit children, whose environment
# snapshot is truncated, and by CI steps that have chdir'd elsewhere; a literal
# is the only form that cannot be perturbed by either.
#
# It names the VERSIONED directory and never the `current` symlink on purpose:
# the GCC driver locates cc1plus relative to its own argv[0], so a PATH pointing
# through `current` would compute a path that disagrees with the prefix compiled
# into the binary.
#
# 'PREFIX_EOF' is quoted so the body is emitted verbatim; only the marked
# substitution below is expanded.
cat > "$PREFIX/activate.sh" <<'PREFIX_EOF'
# Generated by pypto-toolchain build. Do not edit.
export PYPTO_TOOLCHAIN="@PREFIX@"
export PATH="$PYPTO_TOOLCHAIN/bin:$PYPTO_TOOLCHAIN/gcc/bin:$PYPTO_TOOLCHAIN/python/bin:$PATH"
# gcc/lib64 carries the libstdc++ ptoas links against (it needs GLIBCXX_3.4.29;
# the HCE2 system libstdc++ stops at 3.4.28). The ${VAR:+:...} guard keeps an
# empty inherited value from leaving a trailing colon, which the dynamic loader
# reads as "the current directory".
# lib/bundled holds the non-glibc libraries copied out of the build image
# (libffi, libssl, libsqlite3, ...) and goes LAST, so it is a fallback rather
# than an override. Everything launched from this environment inherits
# LD_LIBRARY_PATH, host programs included: with lib/bundled first, HCE2's
# /usr/bin/ssh loaded AlmaLinux's libcrypto.so.1.1 in place of the vendor build
# it was linked against and died on a missing EVP_sm4_ctr. A host that has a
# library keeps its own; one that does not falls through to the bundle's, which
# is all these copies were ever for.
#
# gcc/lib64 stays FIRST and is not a fallback: ptoas needs GLIBCXX_3.4.29 and
# the host libstdc++ stops at 3.4.28, so the bundle's copy has to win there.
export LD_LIBRARY_PATH="$PYPTO_TOOLCHAIN/gcc/lib64:$PYPTO_TOOLCHAIN/python/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}:$PYPTO_TOOLCHAIN/lib/bundled"
PREFIX_EOF

# Substitute the placeholder with the real prefix. Done after the fact so the
# heredoc above can stay fully quoted.
sed -i "s|@PREFIX@|$PREFIX|" "$PREFIX/activate.sh"

# Prove the generated file is sourceable and lands where it claims, here in the
# build rather than on someone's machine an hour later.
# shellcheck disable=SC1090
( set -eu; . "$PREFIX/activate.sh"
  test "$PYPTO_TOOLCHAIN" = "$PREFIX"
  case ":$PATH:" in *":$PREFIX/gcc/bin:"*) ;; *) echo "PATH missing gcc/bin" >&2; exit 1 ;; esac
  case ":$LD_LIBRARY_PATH:" in *":$PREFIX/gcc/lib64:"*) ;; *) echo "LD_LIBRARY_PATH missing gcc/lib64" >&2; exit 1 ;; esac )

echo "generated $PREFIX/activate.sh"
